name: Build Finicky

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: ./scripts/install.sh
      
      - name: Build Finicky
        run: ./scripts/build.sh
      
      - name: Upload Finicky.app
        uses: actions/upload-artifact@v4
        with:
          name: Finicky-with-ASWebAuth
          path: apps/Finicky/build/Build/Products/Release/Finicky.app
          retention-days: 30